#!/usr/bin/python3

import time
import requests
import json
import datetime

outfile = '/etc/traefik-hosts'
configfile = '/etc/traefik-config.json'

config = {}
with open(configfile, 'r') as f:
  config = json.loads(f.read())

scan_interval = int(config['scan_interval'])

print("Host File: " + outfile)
print("Config File: " + configfile)
print("Scan Interval: " + str(scan_interval) + " seconds")


known = {k['url'] : set() for k in config['traefik_instances']}
pending = {}

while (True):
  made_changes = False

  for instance in config['traefik_instances']:
    retrieved = set()
    api_url = instance['url']
    resp = requests.get(api_url)
    if (resp.ok):
      jData = json.loads(resp.content)
      for provKey in jData:
        for frontKey in jData[provKey]['frontends']:
          for routeKey in jData[provKey]['frontends'][frontKey]['routes']:
            rule = jData[provKey]['frontends'][frontKey]['routes'][routeKey]['rule']
            if (rule.startswith("Host:")):
              rule = rule[5:]
              retrieved.add(rule)
    if (known[api_url] != retrieved):
      known[api_url] = retrieved
      for address in instance['addresses']:
        pending[address] = api_url
      made_changes = True

  if (made_changes == True):
    print("Changes found. Re-writing " + str(len(pending)) + " entries")
    with open(outfile, 'w') as f:
      f.write( "# Generated by traefik-hostgen @ " + datetime.datetime.now().isoformat() + " \n")
      for addr in pending:
        f.write(addr + " " + " ".join(str(s) for s in known[pending[addr]]) + "\n")
  time.sleep(scan_interval) 

